<?php 

$dictRubros = array(
"artes_graficas" => "artes_graficas",
"artesanias_y_otros" => "artesanias",
"ecologia_urbana_y_otros" => "ecologia_urbana",
"calzado_marroquineria" => "calzado_marroq",
"envasado_alimentos_bebidas" => "alimentos_bebidas",
"envasado_art_limpieza_tocador" => "art_limpieza",
"indumentaria_prod_textiles" => "ind_prod_text",
"muebles_carpinteria_gral" => "muebles_carp_gral",
"articulos_herreria_metal" => "herreria_metal",
"construccion_nueva" => "constr_obra_nueva",
"enseñanza_capacitacion" => "ensenanza_capac",
"gestion_centro_cultural" => "gest_centro_cult",
"recup_recic_transf_materiales" => "recup_recic_mat",
"servicio_y_recreacion" => "serv_prod_espec",
"repara_calzado_indumentaria_marroq" => "serv_rep_calzado",
"repara_manten_herramientas_maquin" => "serv_rep_mant_herr",
"repara_manten_vehiculos" => "serv_rep_mant_vehic",
"serv_comunitarios_cuidados" => "serv_comun_cuidados",
"serv_comunic_produccion_realiz_audivisual" => "serv_comun_prod",
"serv_de_gastronomia" => "serv_gastronomia",
"serv_manten_repar_gral" => "serv_rep_mant_herr",
"serv_peluqueria_estetica" => "serv_pelu_estet",
"serv_limpieza_mantenim_higiene_urbana" => "serv_limpieza_mant_hig",
"serv_solidarias_recreacion" => "serv_financ",
"serv_tecnologia_software" => "serv_tecn_software",
"serv_transporte_logística" => "serv_transp_logist",
"venta_alimentos_sin_envasar" => "venta_alim_sin_env",
"venta_produc_carniceria_granja_pescader" => "venta_carn_granja_pesc",
"venta_articulos_bazar_kiosco" => "venta_bazar_kiosco",
"venta_ferreteria_electricos_electr_informatica" => "venta_ferret_mat",
"venta_articulos_limpieza_tocador" => "venta_art_limp_toc",
"venta_indumentaria_bijouterie" => "venta_ind_bijout",
"venta_juguetes_libreria" => "venta_jug_lib",
"venta_almacen_bebidas" => "venta_prod_alm",
);

?>
